tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "sanemat/font"
cask "osxfuse"
brew "colordiff"
brew "coreutils"
brew "emacs"
brew "gibo"
brew "git"
brew "htop"
brew "hugo"
brew "iftop"
brew "jq"
brew "mackup"
brew "mas"
brew "mecab"
brew "mecab-ipadic"
brew "nkf"
brew "nmap"
brew "peco"
brew "poetry"
brew "reattach-to-user-namespace"
brew "source-highlight"
brew "sshfs"
brew "tldr"
brew "tmux"
brew "tmux-mem-cpu-load"
brew "tree"
brew "wdiff"
brew "wget"
brew "whalebrew"
brew "zplug"
brew "zsh"
brew "sanemat/font/ricty", args: ["with-powerline"]
cask "adobe-acrobat-reader"
cask "alfred"
cask "appcleaner"
cask "atom"
cask "authy"
cask "bartender"
cask "bettertouchtool"
cask "betterzipql"
cask "cmd-eikana"
cask "docker"
cask "dropbox"
cask "font-hack-nerd-font"
cask "font-noto-sans-cjk-jp"
cask "font-noto-serif-cjk-jp"
cask "fork"
cask "google-backup-and-sync"
cask "google-chrome"
cask "google-japanese-ime"
cask "hammerspoon"
cask "hyperswitch"
cask "insomniax"
cask "istat-menus"
cask "iterm2"
cask "itsycal"
cask "jetbrains-toolbox"
cask "kindle"
cask "kitematic"
cask "mactex"
cask "mathpix-snipping-tool"
cask "ngrok"
cask "qlcolorcode"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlprettypatch"
cask "qlstephen"
cask "qlvideo"
cask "quicklook-csv"
cask "quicklook-json"
cask "quicklookase"
cask "scroll-reverser"
cask "skype"
cask "skype-for-business"
cask "station"
cask "suspicious-package"
cask "tableplus"
cask "texpad"
cask "typora"
cask "visual-studio"
cask "visual-studio-code"
cask "vlc"
cask "webex-meetings"
cask "webpquicklook"
cask "zoomus"
mas "1Password", id: 443987910
mas "BetterSnapTool", id: 417375580
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Microsoft Remote Desktop", id: 1295203466
mas "Slack", id: 803453959
mas "Table Tool", id: 1122008420
mas "The Unarchiver", id: 425424353
mas "WinArchiver Lite", id: 414855915
mas "Xcode", id: 497799835
mas "スケッチ風ドロー", id: 543896183
